name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - main
      - develop

permissions:
  contents: read

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - uses: actions/checkout@v4

      - name: Install Node Dependencies
        run: npm i

      - name: Execute Gradle Build
        run: ./gradlew bootJar

      - uses: actions/upload-artifact@v3
        with:
          name: seizuretracker.jar
          path: build/libs