name: Java CI with Gradle

on:
  push:

permissions:
  contents: read

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1

      - uses: actions/checkout@v4

      - name: Execute Gradle Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: seizuretracker.jar
          path: build/libs

  build_oci_image:
    runs-on: ubuntu-latest
