name: Java CI with Gradle

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: alpine-latest
    container:
      image: amazoncorretto:17-alpine
    steps:
      - name: Install pre-requisite Alpine binaries
        run: apk add nodejs git

      - uses: actions/checkout@v4

      - name: Execute Gradle Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: seizuretracker.jar
          path: build/libs