name: Java CI with Gradle and OCI Image

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - uses: actions/checkout@v4

      - name: Execute Gradle Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: seizuretracker.jar
          path: build/libs

  build_oci_image:
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Checkout (for Dockerfile)
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: seizuretracker.jar

      - name: Build image
        run: docker build . -t git.hlafaille.xyz/hlafaille/seizuretracker:${{ github.ref_name }}

      - name: Registry login
        run: docker login -u ${{ secrets.registry_username }} -p ${{ secrets.registry_password }} git.hlafaille.xyz

      - name: Push image with version tag
        run: docker push git.hlafaille.xyz/hlafaille/seizuretracker:${{ github.ref_name }}

      - name: Push image with latest tag
        run: docker push git.hlafaille.xyz/hlafaille/seizuretracker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_oci_image
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan hlafaille.xyz >> ~/.ssh/known_hosts
      
      - name: Execute remote script
        run: ssh hunter@hlafaille.xyz /pool1/ds_containers/webservices/scripts/seizuretracker/deploy.sh